php_version: 7.4

php_ini: extension=iconv.so
  extension=intl.so
  extension=calendar.so
  extension=pdo.so
  extension=pdo_mysql.so
  extension=zip.so

rules:
  symfony.configuration.error_pages_should_be_customised:
    enabled: false
